name: supabase_registration
description: A simple Flutter app demonstrating Supabase Email authentication.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.5.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
